############################################################
# +------------------------------------------------------+ #
# |                       Заметки                        | #
# +------------------------------------------------------+ #
############################################################
#
#Автор плагина vk.com/red___tea
#
#Плагин распространяется только с согласия его владельца.
#
############################################################
# +------------------------------------------------------+ #
# |                 Основные Настройки                   | #
# +------------------------------------------------------+ #
############################################################
#В некоторых настройках время может указываться знаками ns, nm, nh, nd,
#где n - число, s - секунда, m - минута, h - час, d - день.

settings:

#Боги
gods:

  #Зевс
  Zevs:

    #Засположение статуи
    statue:
      x: 21
      y: 75
      z: -61
      world: world
      #Радиус, входя в который, игрок сможет молиться

      radius: 10
    #Минимальное время между молитвами
    prayerCoolDown: 30m

    trees:
      #Дерево прокачки
      speed:

        #Отображаемое название. Разрешены цветовые коды (к примеру: &4, &l)
        name: '&6Древо скорости'

        #Иконка (предмет), отображаемый в древе
        icon: STONE

        #Слот (номер) расположения иконки древа в меню выбора древ.
        slot: 1

        levels:
          #Уровень молитвы
          1:

            #ЭФФЕКТ:УРОВЕНЬ ЭФФЕКТА
            EFFECT: 'SPEED:1'

            #Кол-во предметов, необходимых, для возвышения
            ITEMS:
              # МАТЕРИАЛ, КОЛ-ВО
              - 'DIAMOND, 1'

          #Уровень молитвы
          2:
            #ЭФФЕКТ:УРОВЕНЬ ЭФФЕКТА
            EFFECT: 'SPEED:2'

            #Кол-во предметов, необходимых, для возвышения
            ITEMS:
              # МАТЕРИАЛ, КОЛ-ВО
              - 'DIAMOND, 1'

      #Дерево прокачки
      protection:

        #Отображаемое название
        name: 'Древо защиты'

        #Иконка (предмет), отображаемый в древе
        icon: STONE

        #Слот (номер) расположения иконки древа в меню выбора древ.
        slot: 2

        levels:

          #Уровень молитвы
          1:

            #ЭФФЕКТ:УРОВЕНЬ ЭФФЕКТА
            EFFECT: 'PROTECTION:1'

            #Кол-во предметов, необходимых, для возвышения
            ITEMS:
              # МАТЕРИАЛ, КОЛ-ВО, Отображаемое имя
              - 'DIAMOND, 1'
              - 'WOOD, 5'

          #Уровень молитвы
          2:
            #ЭФФЕКТ:УРОВЕНЬ ЭФФЕКТА
            EFFECT: 'PROTECTION:2'

            #Кол-во предметов, необходимых, для возвышения
            ITEMS:
              # МАТЕРИАЛ, КОЛ-ВО
              - 'DIAMOND, 3'
              - 'WOOD, 14'

itemsLocalization:
  #Локализация предметов по их id
  - 'DIAMOND:Алмаз'
  - 'WOOD:Дерево'


############################################################
# +------------------------------------------------------+ #
# |                 Сообщения плагина                    | #
# +------------------------------------------------------+ #
############################################################
#Любое сообщение может быть, как списком
#(
#message:
#- '1'
#- '2'
#)
#так и строкой (message: 'String').
messages:

  #Сообщение при отсутствии прав
  noPermissions: '&4&l[!] &cУ вас нет прав!'

  #Сообщение при неправильном использовании команд
  usage:
    - '&a[- Использование команды /prayer -]'
    - '&a/prayer set [игрок] [бог] [ветвь(тег)] [уровень]&e - установить уровень молитвы игроку'
    - '&a/prayer reload &a- перезагрузка плагина'

  notEnoughItems: '&4&l[!] &cУ вас недостаточно предметов для молитвы!'
  prayerSuccess: '&2&l[!] &aВы успешно совершили молитву %prayer%.'
  prayerError: '&4&l[!] &cВы уже открыли эту молитву или у вас не открыты предыдущие молитвы!'

  prayerOpenLore:
    - '&aНажмите, чтобы'
    - '&aполучить эту молитву'
    - '&aЦена'
    - '&a%price%'

  prayerGotLore:
    - '&2Вы уже получили'
    - '&2эту молитву'

  prayerLockedLore:
    - '&cВы не можете'
    - '&cполучить эту молитву'

  commands:
    #Право: prayer.set
    set:
      error: '&4&l[!] &cНе удалось выполнить /prayer set!'
      success: '&2&l[!] &aВы успешно установили игроку новое значение молитвы!'
    reload:
      error: '&4&l[!] &cОшибка во время перезагрузки плагина!'
      success: '&2&l[!] &aПлагин успешно перезагружен за %time% ms!'
